// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrqxKN0PYQlx2wMH-VgWLRAaVIEDBmZoI',
    appId: '1:478828138072:web:c69e22b68de60b5668c42d',
    messagingSenderId: '478828138072',
    projectId: 'kanjinomori',
    authDomain: 'kanjinomori.firebaseapp.com',
    storageBucket: 'kanjinomori.firebasestorage.app',
    measurementId: 'G-TBWTGQTFMD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3PJn_OL9vgzDAZdklNyezbev9z2tWOEY',
    appId: '1:478828138072:android:12625ca8bbf9e5c668c42d',
    messagingSenderId: '478828138072',
    projectId: 'kanjinomori',
    storageBucket: 'kanjinomori.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCasQU2XvjzKEvCL8IhT3Gl3G9U5z3yTRc',
    appId: '1:478828138072:ios:c578b8b67d00e38668c42d',
    messagingSenderId: '478828138072',
    projectId: 'kanjinomori',
    storageBucket: 'kanjinomori.firebasestorage.app',
    iosBundleId: 'com.easyjp.kanjinomori',
  );
}
